#pragma once
#ifndef NIF_NATIVE_PARTICLE_H
#define NIF_NATIVE_PARTICLE_H

#include "NIF.Native.Common.h"

#ifdef __cplusplus
extern "C"
{
#endif

NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_System_Destroy(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY NIF_ParticleSystemHandle NIF_Particle_System_Create(unsigned int maxNumParticles, int normalMethod, NIF_Vec3 normalDirection, int upMethod, NIF_Vec3 upDirection, int hasLivingSpawner, int hasColors, int hasRotations, int hasAnimatedTextures, int worldSpace, int dynamicBounds, int createDefaultGenerator, int attachMeshModifiers, int sorted);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Particle_System_GetMaxNumParticles(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Particle_System_GetNumParticles(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_System_GetLastTime(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY int NIF_Particle_System_HasLivingSpawner(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY int NIF_Particle_System_HasColors(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY int NIF_Particle_System_HasRotations(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY int NIF_Particle_System_HasRotationSpeeds(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY int NIF_Particle_System_HasRotationAxes(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY int NIF_Particle_System_HasAnimatedTextures(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY int NIF_Particle_System_IsSorted(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY int NIF_Particle_System_GetWorldSpace(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_System_SetWorldSpace(NIF_ParticleSystemHandle particleSystem, int worldSpace);
NIFTOOLSET_NATIVE_ENTRY NIF_Transform NIF_Particle_System_GetOriginalWorldTransform(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_System_Reset(NIF_ParticleSystemHandle particleSystem, float newLastTime);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_System_ForceSimulationToComplete(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Particle_System_GetSpawnerCount(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY int NIF_Particle_System_GetNextSpawnTime(NIF_ParticleSystemHandle particleSystem, float time, float age, float lifeSpan, float* outSpawnTime);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_System_GetRunUpTime(NIF_ParticleSystemHandle particleSystem, int includeSpawners);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Particle_System_GetEmitterCount(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY NIF_PSEmitterHandle NIF_Particle_System_GetEmitterAt(NIF_ParticleSystemHandle particleSystem, unsigned int index);
NIFTOOLSET_NATIVE_ENTRY NIF_PSEmitterHandle NIF_Particle_System_GetEmitterByName(NIF_ParticleSystemHandle particleSystem, const char* name);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_System_AddEmitter(NIF_ParticleSystemHandle particleSystem, NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_System_RemoveEmitterAt(NIF_ParticleSystemHandle particleSystem, unsigned int index, int maintainOrder);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_System_RemoveAllEmitters(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY NIF_MeshHandle NIF_Particle_System_AsMesh(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY NIF_AVObjectHandle NIF_Particle_System_AsAVObject(NIF_ParticleSystemHandle particleSystem);
NIFTOOLSET_NATIVE_ENTRY NIF_ObjectHandle NIF_Particle_System_AsObject(NIF_ParticleSystemHandle particleSystem);

NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_Destroy(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY const char* NIF_Particle_Emitter_GetName(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetName(NIF_PSEmitterHandle emitter, const char* name);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetSpeed(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetSpeed(NIF_PSEmitterHandle emitter, float speed);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetSpeedVar(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetSpeedVar(NIF_PSEmitterHandle emitter, float speedVar);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetSpeedFlipRatio(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetSpeedFlipRatio(NIF_PSEmitterHandle emitter, float speedFlipRatio);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetLifeSpan(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetLifeSpan(NIF_PSEmitterHandle emitter, float lifeSpan);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetLifeSpanVar(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetLifeSpanVar(NIF_PSEmitterHandle emitter, float lifeSpanVar);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetDeclination(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetDeclination(NIF_PSEmitterHandle emitter, float declination);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetDeclinationVar(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetDeclinationVar(NIF_PSEmitterHandle emitter, float declinationVar);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetPlanarAngle(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetPlanarAngle(NIF_PSEmitterHandle emitter, float planarAngle);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetPlanarAngleVar(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetPlanarAngleVar(NIF_PSEmitterHandle emitter, float planarAngleVar);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetSize(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetSize(NIF_PSEmitterHandle emitter, float size);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetSizeVar(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetSizeVar(NIF_PSEmitterHandle emitter, float sizeVar);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetRotAngle(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetRotAngle(NIF_PSEmitterHandle emitter, float rotAngle);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetRotAngleVar(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetRotAngleVar(NIF_PSEmitterHandle emitter, float rotAngleVar);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetRotSpeed(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetRotSpeed(NIF_PSEmitterHandle emitter, float rotSpeed);
NIFTOOLSET_NATIVE_ENTRY float NIF_Particle_Emitter_GetRotSpeedVar(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetRotSpeedVar(NIF_PSEmitterHandle emitter, float rotSpeedVar);
NIFTOOLSET_NATIVE_ENTRY int NIF_Particle_Emitter_GetRandomRotSpeedSign(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetRandomRotSpeedSign(NIF_PSEmitterHandle emitter, int randomRotSpeedSign);
NIFTOOLSET_NATIVE_ENTRY NIF_Vec3 NIF_Particle_Emitter_GetRotAxis(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetRotAxis(NIF_PSEmitterHandle emitter, NIF_Vec3 rotAxis);
NIFTOOLSET_NATIVE_ENTRY int NIF_Particle_Emitter_GetRandomRotAxis(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_SetRandomRotAxis(NIF_PSEmitterHandle emitter, int randomRotAxis);
NIFTOOLSET_NATIVE_ENTRY void NIF_Particle_Emitter_ResetTransformation(NIF_PSEmitterHandle emitter);
NIFTOOLSET_NATIVE_ENTRY NIF_ObjectHandle NIF_Particle_Emitter_AsObject(NIF_PSEmitterHandle emitter);

#ifdef __cplusplus
}
#endif

#endif // NIF_NATIVE_PARTICLE_H
