#pragma once
#ifndef NIF_NATIVE_COLLISION_H
#define NIF_NATIVE_COLLISION_H

#include "NIF.Native.Common.h"

#ifdef __cplusplus
extern "C"
{
#endif

typedef struct NIF_CollisionIntersectDesc
{
	NIF_AVObjectHandle root0;
	NIF_AVObjectHandle root1;
	NIF_AVObjectHandle object0;
	NIF_AVObjectHandle object1;
	float time;
	NIF_Vec3 point;
	NIF_Vec3 normal0;
	NIF_Vec3 normal1;
} NIF_CollisionIntersectDesc;

// Releases all owned handles stored in the result and resets every field.
// C# callers should invoke this in a finally block after a successful query.
NIFTOOLSET_NATIVE_ENTRY void NIF_CollisionIntersectDesc_Release(NIF_CollisionIntersectDesc* intersect);

typedef struct NIF_CollisionTriangleDesc
{
	NIF_Vec3 point0;
	NIF_Vec3 point1;
	NIF_Vec3 point2;
} NIF_CollisionTriangleDesc;

NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_Destroy(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY NIF_ObjectHandle NIF_Collision_Data_AsObject(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY NIF_CollisionDataHandle NIF_Collision_Data_Create(NIF_AVObjectHandle sceneObject);
NIFTOOLSET_NATIVE_ENTRY NIF_AVObjectHandle NIF_Collision_Data_GetSceneObject(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_SetPropagationMode(NIF_CollisionDataHandle collisionData, int propagationMode);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Data_GetPropagationMode(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_SetCollisionMode(NIF_CollisionDataHandle collisionData, int collisionMode);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Data_GetCollisionMode(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_SetLocalVelocity(NIF_CollisionDataHandle collisionData, NIF_Vec3 velocity);
NIFTOOLSET_NATIVE_ENTRY NIF_Vec3 NIF_Collision_Data_GetLocalVelocity(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_SetWorldVelocity(NIF_CollisionDataHandle collisionData, NIF_Vec3 velocity);
NIFTOOLSET_NATIVE_ENTRY NIF_Vec3 NIF_Collision_Data_GetWorldVelocity(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_SetEnableAuxCallbacks(NIF_CollisionDataHandle collisionData, int enable);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Data_GetEnableAuxCallbacks(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_CreateWorldVertices(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_UpdateWorldVertices(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_DestroyWorldVertices(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_CreateWorldNormals(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_UpdateWorldNormals(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_DestroyWorldNormals(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_MarkVerticesAsChanged(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_MarkNormalsAsChanged(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Collision_Data_GetTriangleCount(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Data_GetWorldTriangle(NIF_CollisionDataHandle collisionData, unsigned int triangleIndex, NIF_CollisionTriangleDesc* triangle);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Data_HasModelSpaceABV(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Data_HasWorldSpaceABV(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Data_GetModelSpaceABVType(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Data_GetWorldSpaceABVType(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Collision_Data_GetModelSpaceABVIntersectObjectIndex(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Collision_Data_GetWorldSpaceABVIntersectObjectIndex(NIF_CollisionDataHandle collisionData);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Data_TestABVIntersect(NIF_CollisionDataHandle collisionData0, NIF_CollisionDataHandle collisionData1, float deltaTime);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Data_FindABVIntersect(NIF_CollisionDataHandle collisionData0, NIF_CollisionDataHandle collisionData1, float deltaTime, int calculateNormals, NIF_CollisionIntersectDesc* intersect);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Data_GetCollisionTestType(NIF_AVObjectHandle object0, NIF_AVObjectHandle object1);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Data_ValidateForCollision(NIF_AVObjectHandle objectHandle, int collisionMode);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Data_SetEnableVelocity(int enable);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Data_GetEnableVelocity(void);

NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Group_Destroy(NIF_CollisionGroupHandle collisionGroup);
NIFTOOLSET_NATIVE_ENTRY NIF_CollisionGroupHandle NIF_Collision_Group_Create(void);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Group_AddCollider(NIF_CollisionGroupHandle collisionGroup, NIF_AVObjectHandle objectHandle, int createCollisionData, int maxDepth, int binSize);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Group_AddCollidee(NIF_CollisionGroupHandle collisionGroup, NIF_AVObjectHandle objectHandle, int createCollisionData, int maxDepth, int binSize);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Group_RemoveCollider(NIF_CollisionGroupHandle collisionGroup, NIF_AVObjectHandle objectHandle);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Group_RemoveCollidee(NIF_CollisionGroupHandle collisionGroup, NIF_AVObjectHandle objectHandle);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Group_Remove(NIF_CollisionGroupHandle collisionGroup, NIF_AVObjectHandle objectHandle);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Group_RemoveAll(NIF_CollisionGroupHandle collisionGroup);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Group_IsCollider(NIF_CollisionGroupHandle collisionGroup, NIF_AVObjectHandle objectHandle);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Group_IsCollidee(NIF_CollisionGroupHandle collisionGroup, NIF_AVObjectHandle objectHandle);
NIFTOOLSET_NATIVE_ENTRY void NIF_Collision_Group_UpdateWorldData(NIF_CollisionGroupHandle collisionGroup);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Group_TestCollisions(NIF_CollisionGroupHandle collisionGroup, float deltaTime);
NIFTOOLSET_NATIVE_ENTRY int NIF_Collision_Group_FindCollisions(NIF_CollisionGroupHandle collisionGroup, float deltaTime);

#ifdef __cplusplus
}
#endif

#endif // NIF_NATIVE_COLLISION_H
