#pragma once
#ifndef NIF_NATIVE_RENDER_PIPELINE_H
#define NIF_NATIVE_RENDER_PIPELINE_H

#include "NIF.Native.Common.h"

#ifdef __cplusplus
extern "C"
{
#endif

NIFTOOLSET_NATIVE_ENTRY void NIF_AlphaAccumulator_Destroy(NIF_AlphaAccumulatorHandle accumulator);
NIFTOOLSET_NATIVE_ENTRY NIF_AlphaAccumulatorHandle NIF_AlphaAccumulator_Create(void);
NIFTOOLSET_NATIVE_ENTRY void NIF_AlphaAccumulator_SetObserveNoSortHint(NIF_AlphaAccumulatorHandle accumulator, int observe);
NIFTOOLSET_NATIVE_ENTRY int NIF_AlphaAccumulator_GetObserveNoSortHint(NIF_AlphaAccumulatorHandle accumulator);
NIFTOOLSET_NATIVE_ENTRY void NIF_AlphaAccumulator_SetSortByClosestPoint(NIF_AlphaAccumulatorHandle accumulator, int sortByClosestPoint);
NIFTOOLSET_NATIVE_ENTRY int NIF_AlphaAccumulator_GetSortByClosestPoint(NIF_AlphaAccumulatorHandle accumulator);

NIFTOOLSET_NATIVE_ENTRY void NIF_RenderListProcessor_Destroy(NIF_RenderListProcessorHandle processor);
NIFTOOLSET_NATIVE_ENTRY void NIF_AlphaSortProcessor_Destroy(NIF_AlphaSortProcessorHandle processor);
NIFTOOLSET_NATIVE_ENTRY NIF_AlphaSortProcessorHandle NIF_AlphaSortProcessor_Create(int observeNoSortHint, int sortByClosestPoint);
NIFTOOLSET_NATIVE_ENTRY int NIF_AlphaSortProcessor_AsRenderListProcessor(NIF_AlphaSortProcessorHandle processor, NIF_RenderListProcessorHandle* outProcessor);
NIFTOOLSET_NATIVE_ENTRY void NIF_AlphaSortProcessor_SetObserveNoSortHint(NIF_AlphaSortProcessorHandle processor, int observeNoSortHint);
NIFTOOLSET_NATIVE_ENTRY int NIF_AlphaSortProcessor_GetObserveNoSortHint(NIF_AlphaSortProcessorHandle processor);

NIFTOOLSET_NATIVE_ENTRY void NIF_CullingProcess_Destroy(NIF_CullingProcessHandle cullingProcess);
NIFTOOLSET_NATIVE_ENTRY void NIF_MeshCullingProcess_Destroy(NIF_MeshCullingProcessHandle cullingProcess);
NIFTOOLSET_NATIVE_ENTRY NIF_MeshCullingProcessHandle NIF_MeshCullingProcess_Create(void);
NIFTOOLSET_NATIVE_ENTRY int NIF_MeshCullingProcess_AsCullingProcess(NIF_MeshCullingProcessHandle cullingProcess, NIF_CullingProcessHandle* outCullingProcess);

NIFTOOLSET_NATIVE_ENTRY void NIF_RenderView_Destroy(NIF_RenderViewHandle renderView);
NIFTOOLSET_NATIVE_ENTRY const char* NIF_RenderView_GetName(NIF_RenderViewHandle renderView);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderView_SetName(NIF_RenderViewHandle renderView, const char* name);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderView_ClearCachedPVGeometry(NIF_RenderViewHandle renderView);

NIFTOOLSET_NATIVE_ENTRY void NIF_RenderView3D_Destroy(NIF_RenderView3DHandle renderView);
NIFTOOLSET_NATIVE_ENTRY NIF_RenderView3DHandle NIF_RenderView3D_Create(NIF_CameraHandle camera, NIF_CullingProcessHandle cullingProcess, int alwaysUseCameraViewport);
NIFTOOLSET_NATIVE_ENTRY int NIF_RenderView3D_AsRenderView(NIF_RenderView3DHandle renderView, NIF_RenderViewHandle* outRenderView);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderView3D_SetCamera(NIF_RenderView3DHandle renderView, NIF_CameraHandle camera);
NIFTOOLSET_NATIVE_ENTRY NIF_CameraHandle NIF_RenderView3D_GetCamera(NIF_RenderView3DHandle renderView);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderView3D_SetCullingProcess(NIF_RenderView3DHandle renderView, NIF_CullingProcessHandle cullingProcess);
NIFTOOLSET_NATIVE_ENTRY NIF_CullingProcessHandle NIF_RenderView3D_GetCullingProcess(NIF_RenderView3DHandle renderView);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderView3D_SetAlwaysUseCameraViewport(NIF_RenderView3DHandle renderView, int alwaysUseCameraViewport);
NIFTOOLSET_NATIVE_ENTRY int NIF_RenderView3D_GetAlwaysUseCameraViewport(NIF_RenderView3DHandle renderView);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderView3D_AppendScene(NIF_RenderView3DHandle renderView, NIF_AVObjectHandle scene);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderView3D_PrependScene(NIF_RenderView3DHandle renderView, NIF_AVObjectHandle scene);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderView3D_RemoveScene(NIF_RenderView3DHandle renderView, NIF_AVObjectHandle scene);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderView3D_RemoveAllScenes(NIF_RenderView3DHandle renderView);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_RenderView3D_GetSceneCount(NIF_RenderView3DHandle renderView);
NIFTOOLSET_NATIVE_ENTRY NIF_AVObjectHandle NIF_RenderView3D_GetSceneAt(NIF_RenderView3DHandle renderView, unsigned int index);

NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_Destroy(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY const char* NIF_RenderClick_GetName(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_SetName(NIF_RenderClickHandle renderClick, const char* name);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_SetClearAllBuffers(NIF_RenderClickHandle renderClick, int clearAllBuffers);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_SetClearColorBuffers(NIF_RenderClickHandle renderClick, int clearColorBuffers);
NIFTOOLSET_NATIVE_ENTRY int NIF_RenderClick_GetClearColorBuffers(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_SetClearDepthBuffer(NIF_RenderClickHandle renderClick, int clearDepthBuffer);
NIFTOOLSET_NATIVE_ENTRY int NIF_RenderClick_GetClearDepthBuffer(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_SetClearStencilBuffer(NIF_RenderClickHandle renderClick, int clearStencilBuffer);
NIFTOOLSET_NATIVE_ENTRY int NIF_RenderClick_GetClearStencilBuffer(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_RequestClearAllBuffersOnce(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_RequestClearColorBuffersOnce(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_RequestClearDepthBufferOnce(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_RequestClearStencilBufferOnce(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_SetBackgroundColor(NIF_RenderClickHandle renderClick, NIF_ColorA color);
NIFTOOLSET_NATIVE_ENTRY NIF_ColorA NIF_RenderClick_GetBackgroundColor(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_SetUseRendererBackgroundColor(NIF_RenderClickHandle renderClick, int useRendererBackgroundColor);
NIFTOOLSET_NATIVE_ENTRY int NIF_RenderClick_GetUseRendererBackgroundColor(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_SetPersistBackgroundColorToRenderer(NIF_RenderClickHandle renderClick, int persist);
NIFTOOLSET_NATIVE_ENTRY int NIF_RenderClick_GetPersistBackgroundColorToRenderer(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_SetViewport(NIF_RenderClickHandle renderClick, NIF_Rect viewport);
NIFTOOLSET_NATIVE_ENTRY NIF_Rect NIF_RenderClick_GetViewport(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_SetActive(NIF_RenderClickHandle renderClick, int active);
NIFTOOLSET_NATIVE_ENTRY int NIF_RenderClick_GetActive(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_SetRenderTargetGroup(NIF_RenderClickHandle renderClick, NIF_RenderTargetGroupHandle renderTargetGroup);
NIFTOOLSET_NATIVE_ENTRY int NIF_RenderClick_GetRenderTargetGroup(NIF_RenderClickHandle renderClick, NIF_RenderTargetGroupHandle* outRenderTargetGroup);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_SetRenderTargetGroupDefault(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_Render(NIF_RenderClickHandle renderClick, unsigned int frameId);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_RenderClick_GetNumObjectsDrawn(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY float NIF_RenderClick_GetCullTime(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY float NIF_RenderClick_GetRenderTime(NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderClick_ReleaseCaches(NIF_RenderClickHandle renderClick);

NIFTOOLSET_NATIVE_ENTRY void NIF_ViewRenderClick_Destroy(NIF_ViewRenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY NIF_ViewRenderClickHandle NIF_ViewRenderClick_Create(void);
NIFTOOLSET_NATIVE_ENTRY int NIF_ViewRenderClick_AsRenderClick(NIF_ViewRenderClickHandle renderClick, NIF_RenderClickHandle* outRenderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_ViewRenderClick_AppendRenderView(NIF_ViewRenderClickHandle renderClick, NIF_RenderViewHandle renderView);
NIFTOOLSET_NATIVE_ENTRY void NIF_ViewRenderClick_PrependRenderView(NIF_ViewRenderClickHandle renderClick, NIF_RenderViewHandle renderView);
NIFTOOLSET_NATIVE_ENTRY void NIF_ViewRenderClick_RemoveRenderView(NIF_ViewRenderClickHandle renderClick, NIF_RenderViewHandle renderView);
NIFTOOLSET_NATIVE_ENTRY void NIF_ViewRenderClick_RemoveAllRenderViews(NIF_ViewRenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_ViewRenderClick_SetProcessor(NIF_ViewRenderClickHandle renderClick, NIF_RenderListProcessorHandle processor);
NIFTOOLSET_NATIVE_ENTRY int NIF_ViewRenderClick_GetProcessor(NIF_ViewRenderClickHandle renderClick, NIF_RenderListProcessorHandle* outProcessor);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_ViewRenderClick_GetRenderViewCount(NIF_ViewRenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY NIF_RenderViewHandle NIF_ViewRenderClick_GetRenderViewAt(NIF_ViewRenderClickHandle renderClick, unsigned int index);

NIFTOOLSET_NATIVE_ENTRY void NIF_RenderStep_Destroy(NIF_RenderStepHandle renderStep);
NIFTOOLSET_NATIVE_ENTRY const char* NIF_RenderStep_GetName(NIF_RenderStepHandle renderStep);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderStep_SetName(NIF_RenderStepHandle renderStep, const char* name);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderStep_Render(NIF_RenderStepHandle renderStep);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderStep_SetActive(NIF_RenderStepHandle renderStep, int active);
NIFTOOLSET_NATIVE_ENTRY int NIF_RenderStep_GetActive(NIF_RenderStepHandle renderStep);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderStep_SetPreCallback(NIF_RenderStepHandle renderStep, NIF_RenderStepCallback callback, void* userData);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderStep_SetPostCallback(NIF_RenderStepHandle renderStep, NIF_RenderStepCallback callback, void* userData);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderStep_ClearCallbacks(NIF_RenderStepHandle renderStep);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_RenderStep_GetNumObjectsDrawn(NIF_RenderStepHandle renderStep);
NIFTOOLSET_NATIVE_ENTRY float NIF_RenderStep_GetCullTime(NIF_RenderStepHandle renderStep);
NIFTOOLSET_NATIVE_ENTRY float NIF_RenderStep_GetRenderTime(NIF_RenderStepHandle renderStep);
NIFTOOLSET_NATIVE_ENTRY void NIF_RenderStep_ReleaseCaches(NIF_RenderStepHandle renderStep);
NIFTOOLSET_NATIVE_ENTRY int NIF_RenderStep_SetOutputRenderTargetGroup(NIF_RenderStepHandle renderStep, NIF_RenderTargetGroupHandle renderTargetGroup);
NIFTOOLSET_NATIVE_ENTRY int NIF_RenderStep_GetOutputRenderTargetGroup(NIF_RenderStepHandle renderStep, NIF_RenderTargetGroupHandle* outRenderTargetGroup);
NIFTOOLSET_NATIVE_ENTRY void NIF_DefaultClickRenderStep_Destroy(NIF_DefaultClickRenderStepHandle renderStep);
NIFTOOLSET_NATIVE_ENTRY NIF_DefaultClickRenderStepHandle NIF_DefaultClickRenderStep_Create(void);
NIFTOOLSET_NATIVE_ENTRY int NIF_DefaultClickRenderStep_AsRenderStep(NIF_DefaultClickRenderStepHandle renderStep, NIF_RenderStepHandle* outRenderStep);
NIFTOOLSET_NATIVE_ENTRY void NIF_DefaultClickRenderStep_AppendRenderClick(NIF_DefaultClickRenderStepHandle renderStep, NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_DefaultClickRenderStep_PrependRenderClick(NIF_DefaultClickRenderStepHandle renderStep, NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_DefaultClickRenderStep_RemoveRenderClick(NIF_DefaultClickRenderStepHandle renderStep, NIF_RenderClickHandle renderClick);
NIFTOOLSET_NATIVE_ENTRY void NIF_DefaultClickRenderStep_RemoveAllRenderClicks(NIF_DefaultClickRenderStepHandle renderStep);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_DefaultClickRenderStep_GetRenderClickCount(NIF_DefaultClickRenderStepHandle renderStep);
NIFTOOLSET_NATIVE_ENTRY NIF_RenderClickHandle NIF_DefaultClickRenderStep_GetRenderClickAt(NIF_DefaultClickRenderStepHandle renderStep, unsigned int index);

#ifdef __cplusplus
}
#endif

#endif // NIF_NATIVE_RENDER_PIPELINE_H
