#pragma once
#ifndef NIF_NATIVE_FLOODGATE_H
#define NIF_NATIVE_FLOODGATE_H

#include "NIF.Native.Common.h"

#ifdef __cplusplus
extern "C"
{
#endif

typedef struct NIF_FloodgateTaskHandle_t* NIF_FloodgateTaskHandle;
typedef struct NIF_FloodgateWorkflowHandle_t* NIF_FloodgateWorkflowHandle;
typedef struct NIF_FloodgateStreamHandle_t* NIF_FloodgateStreamHandle;

NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Task_Destroy(NIF_FloodgateTaskHandle task);
NIFTOOLSET_NATIVE_ENTRY NIF_FloodgateTaskHandle NIF_Floodgate_Task_Create(unsigned short inputCount, unsigned short outputCount);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Task_Clear(NIF_FloodgateTaskHandle task, int ignoreCaching);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Floodgate_Task_GetInputCount(NIF_FloodgateTaskHandle task);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Floodgate_Task_GetOutputCount(NIF_FloodgateTaskHandle task);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Task_SetBlockCount(NIF_FloodgateTaskHandle task, unsigned int blockCount);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Floodgate_Task_GetBlockCount(NIF_FloodgateTaskHandle task);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Task_SetDataDecompositionEnabled(NIF_FloodgateTaskHandle task, int enabled);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Task_IsDataDecompositionEnabled(NIF_FloodgateTaskHandle task);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Task_SetCacheable(NIF_FloodgateTaskHandle task, int cacheable);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Task_IsCacheable(NIF_FloodgateTaskHandle task);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Task_SetCompacted(NIF_FloodgateTaskHandle task, int compacted);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Task_IsCompacted(NIF_FloodgateTaskHandle task);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Task_AddInput(NIF_FloodgateTaskHandle task, NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Task_AddOutput(NIF_FloodgateTaskHandle task, NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Task_RemoveInput(NIF_FloodgateTaskHandle task, NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Task_RemoveOutput(NIF_FloodgateTaskHandle task, NIF_FloodgateStreamHandle stream);

NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Workflow_Destroy(NIF_FloodgateWorkflowHandle workflow);
NIFTOOLSET_NATIVE_ENTRY NIF_FloodgateWorkflowHandle NIF_Floodgate_Workflow_Create(void);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Workflow_Clear(NIF_FloodgateWorkflowHandle workflow);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Workflow_Reset(NIF_FloodgateWorkflowHandle workflow);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Floodgate_Workflow_GetTaskCount(NIF_FloodgateWorkflowHandle workflow);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Workflow_AddTask(NIF_FloodgateWorkflowHandle workflow, NIF_FloodgateTaskHandle task);
NIFTOOLSET_NATIVE_ENTRY NIF_FloodgateTaskHandle NIF_Floodgate_Workflow_AddNewTask(NIF_FloodgateWorkflowHandle workflow, unsigned short inputCount, unsigned short outputCount);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Workflow_GetStatus(NIF_FloodgateWorkflowHandle workflow);

NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Processor_IsAvailable(void);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Floodgate_Processor_GetWorkerThreadCount(void);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Processor_SetWorkerThreadCount(unsigned int workerThreadCount);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Processor_GetParallelExecution(void);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Processor_SetParallelExecution(int parallelExecution);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Processor_Submit(NIF_FloodgateWorkflowHandle workflow, int priority);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Processor_Poll(NIF_FloodgateWorkflowHandle workflow);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Processor_Wait(NIF_FloodgateWorkflowHandle workflow, unsigned int timeout);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Processor_Clear(NIF_FloodgateWorkflowHandle workflow);

NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Stream_Destroy(NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY NIF_FloodgateStreamHandle NIF_Floodgate_Stream_Create(void* data, unsigned int stride, unsigned int blockCount, int fixedInput);
NIFTOOLSET_NATIVE_ENTRY void* NIF_Floodgate_Stream_GetData(NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Stream_SetData(NIF_FloodgateStreamHandle stream, void* data);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Floodgate_Stream_GetStride(NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Stream_SetStride(NIF_FloodgateStreamHandle stream, unsigned int stride);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Floodgate_Stream_GetBlockCount(NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Stream_SetBlockCount(NIF_FloodgateStreamHandle stream, unsigned int blockCount);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Stream_IsFixedInput(NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY int NIF_Floodgate_Stream_GetAutoSetBlockCount(NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Stream_SetAutoSetBlockCount(NIF_FloodgateStreamHandle stream, int autoSetBlockCount);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Floodgate_Stream_GetRegionIndex(NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Stream_SetRegionIndex(NIF_FloodgateStreamHandle stream, unsigned int regionIndex);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Floodgate_Stream_GetElementOffset(NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Stream_SetElementOffset(NIF_FloodgateStreamHandle stream, unsigned int elementOffset);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Stream_SetDataSource(NIF_FloodgateStreamHandle stream, NIF_DataStreamHandle dataStream, int autoSetBlockCount, unsigned int regionIndex, unsigned int elementOffset);
NIFTOOLSET_NATIVE_ENTRY NIF_DataStreamHandle NIF_Floodgate_Stream_GetDataSource(NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Floodgate_Stream_GetInputCount(NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Floodgate_Stream_GetOutputCount(NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY unsigned int NIF_Floodgate_Stream_GetDataSize(NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Stream_Prepare(NIF_FloodgateStreamHandle stream);
NIFTOOLSET_NATIVE_ENTRY void NIF_Floodgate_Stream_ClearTaskArrays(NIF_FloodgateStreamHandle stream);

#ifdef __cplusplus
}
#endif

#endif // NIF_NATIVE_FLOODGATE_H
