// EMERGENT GAME TECHNOLOGIES PROPRIETARY INFORMATION
//
// This software is supplied under the terms of a license agreement or
// nondisclosure agreement with Emergent Game Technologies and may not
// be copied or disclosed except in accordance with the terms of that
// agreement.
//
//      Copyright (c) 1996-2009 Emergent Game Technologies.
//      All Rights Reserved.
//
// Emergent Game Technologies, Calabasas, CA 91302
// http://www.emergent.net

#ifndef NITERRAINSECTORSELECTORPAGER
#define NITERRAINSECTORSELECTORPAGER

#include <utility>
#include "NiTerrainLibType.h"
#include "NiTerrainSectorSelector.h"

class NiTerrain;

/**
    This class is an implementation of the NiTerrainSectorSelector interface, and allows
    developers to quickly introduce paging behavior and algorithms to their terrain scenes. 
    The set of sectors to be loaded are defined by a set of pager objects that may be implemented
    in many different ways.
*/
class NITERRAIN_ENTRY NiTerrainSectorSelectorPager : public NiTerrainSectorSelector
{
    /// @cond EMERGENT_INTERNAL
    NiDeclareRTTI;
    /// @endcond
public:

    /**
        A class to represent a request to load a sector to a particular level of detail and a 
        priority value to represent how important this request is. 
    */
    struct SectorRequest
    {
        /**
            Default constructor with default values of 'lowest priority' and to 'unload' a sector. 
        */
        SectorRequest();

        /// The target LOD to load the sector to.
        efd::SInt32 m_iTargetLOD;
        /// A priority value to prioritize this request against other requests. 
        efd::Float32 m_fPriorityMetric;
    };

    /// Typedef for a map of sectorID's to target level of details to represent sector requests
    typedef efd::map<NiTerrainSector::SectorID, SectorRequest> SectorRequestSet;

    /**
        An abstract class used to represent an object that specifies a set of sectors that need to
        be loaded into memory. Subclasses of this object can be used to generate a set of sectors
        based on arbitrary algorithms.
    */
    class Pager
    {
        EE_DECLARE_ABSTRACT_REFCOUNT;

    public:
        /// Is the pager object active
        bool IsActive() const;
        /// Is the pager object dynamic/static
        bool IsDynamic() const;
        /// Does the pager object's selection set need recalculating?
        bool IsDirty() const;
        /// Has the mode changed since the last calculation
        bool IsModeDirty() const;
        /// Get the priority of this pager
        efd::Float32 GetPriority() const;
        /// Get the latest list of requests from the pager
        const SectorRequestSet& GetRequests() const;

        /**
            Calculate the list of sectors to load. This function is called whenever a terrain is 
            trying to determine if any sectors need streaming and this pager object
            is static and dirty, or dynamic. 
        */
        void CalculateRequests();

        /**
            Append a sector request, specifying the sector to load and the LOD to load it to. If
            a request already exists in the map then the lower priority value and higher LOD 
            value will be used.

            @param iSectorX The x index of the sector the request is for.
            @param iSectorY The y index of the sector the request is for.
            @param iTargetLOD The LOD to request the sector be loaded to.
            @param fPriority A priority to assign to this request to be compared to other requests.
            Requests of lower values will be considered for execution first. 
        */
        void AppendRequest(efd::SInt16 iSectorX, efd::SInt16 iSectorY, efd::SInt32 iTargetLOD,
            efd::Float32 fPriority = 0.0f);

        /**
            Clear all requests from the pager object.
        */
        void ClearRequests();

    protected:
        /// Destructor
        virtual ~Pager();

        /// Constructor
        Pager();

        /**
            Virtual function to be overridden by subclasses wishing to implement a sector selection
            algorithm.
        */
        virtual void CalculateRequests_Internal() = 0;

        /// Has the pager changed mode since the last update
        bool m_bModeChanged;
        /// Is the pager object active
        bool m_bIsActive;
        /// Does the pager object's selection set need recalculating?
        bool m_bIsDirty;
        /// Is the pager object dynamic
        bool m_bIsDynamic;
        /// The priority offset of this pager object
        efd::Float32 m_fPriority;
        /// The list of sector requests that were last generated by this object
        SectorRequestSet m_kSectorRequests;
    };

    /**
        Constructor
        @param pkTerrain The terrain the selector will be working with.
    */
    NiTerrainSectorSelectorPager(NiTerrain* pkTerrain);

    /**
        Destructor
    */
    virtual ~NiTerrainSectorSelectorPager();

    /**
        Updates the sector selection according to the given terrain.
    */
    virtual bool UpdateSectorSelection();
    
    /**
        Register a pager object with the sector selector to be queried to find out what sectors
        should be loaded in the scene.

        @param pkPager The pager object to register.
    */
    void RegisterPager(Pager* pkPager);

    /**
        Remove a pager object from the sector selector

        @param pkPager The pager object to unregister.
    */
    void DeregisterPager(Pager* pkPager);

    /**
        Remove all pagers from the sector selector
    */
    void ClearPagers();

protected:

    /// Typedef to represent a complete request object including sectorID and the sector request.
    typedef std::pair<NiTerrainSector::SectorID, SectorRequest> CompleteSectorRequest;

    /**
        Merge two sector request sets together. The first sector set will have the values from the
        second set merged into it. Higher LOD values will overwrite lower, and lower priority values
        will overwrite higher ones.

        @param kSetA The set to be merged into.
        @param kSetB The set to have it's items added to kSetA.
        @param fSetBPriority A priority offset to apply to kSetB's requests.
    */
    void MergeSectorSet(SectorRequestSet& kSetA, const SectorRequestSet& kSetB, 
        efd::Float32 fSetBPriority = 0.0f);

    /**
        Generate a sequence of streaming requests based on a set of sectors that should be 
        currently loaded into memory. Sectors that have been loaded that are no longer requested
        will be flagged for unloading.

        @param kRequests The set of requests to turn into a sorted list of commands.
    */
    bool GenerateStreamingRequests(SectorRequestSet& kRequests);

    /**
        A static sort function defined to sort a list of CompleteSectorRequests according to
        their priority. Lower priority values will be moved to the front of the list for execution
        first.

        @param kRequestA The left operand of the comparison.
        @param kRequestB The right operand of the comparison.
        @return The result of a less than comparison of the two operand's priority values.
    */
    static bool SortByPriority(const CompleteSectorRequest& kRequestA,
        const CompleteSectorRequest& kRequestB);

    /// Typedef for a list of pager objects
    typedef efd::vector<NiPointer<Pager> > PagerList;
    /// The list of pager objects user to determine what sectors are required in the scene.
    PagerList m_kPagers;
    /// The list of static sector requests from all static pager objects.
    SectorRequestSet m_kStaticSectorRequests;

};
/// Typedef for a smart pointer to a NiTerrainSectorSelectorPager.
NiSmartPointer(NiTerrainSectorSelectorPager);

#include "NiTerrainSectorSelectorPager.inl"

#endif